api:
  key: UserUserUserUserUserUserUserUserUserUser_kzQiO6JzTQu4aqjtCcKtMcKLRxyCqZ7O0Omo0BQTpLwgaapYZCu1cMX0wTLp0WYt

base:
  url: https://demo.reportportal.io/api/v1
  projectName: default_personal

url:
  launches: https://demo.reportportal.io/ui/#default_personal/launches/all