name: CI + Allure

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Create application.yaml from GitHub Secret
        env:
          RP_API_KEY: ${{ secrets.RP_API_KEY }}
        run: |
          cat > src/test/resources/application.yaml << EOF
          api:
            key: ${RP_API_KEY}

          base:
            url: https://demo.reportportal.io/api/v1
            projectName: default_personal

          url:
            launches: https://demo.reportportal.io/ui/#default_personal/launches/all
          EOF

      - name: Run API Tests
        run: mvn -B test -DsuiteXmlFile=src/test/resources/testng-api.xml

      - name: Run UI Tests
        run: mvn -B test -DsuiteXmlFile=src/test/resources/testng-ui.xml

      - name: Generate Allure Report
        if: always()
        run: mvn -B allure:report

      - name: Debug allure-results
        if: always()
        run: |
          echo "=== target/allure-results ==="
          ls -la target/allure-results || true
          echo "Files count:"
          find target/allure-results -type f | wc -l || true

      - name: Prepare public folder (Allure Maven)
        if: always()
        run: |
          rm -rf public
          mkdir -p public
          cp -R target/site/* public/

          if [ -f public/allure-maven.html ]; then
            mv public/allure-maven.html public/index.html
          fi

          echo "=== Public root ==="
          ls -la public

          if [ ! -f public/index.html ]; then
            echo "ERROR: index.html not found"
            exit 1
          fi

      - name: Deploy Allure report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

