name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Create application.yaml from GitHub Secret
        env:
          RP_API_KEY: ${{ secrets.RP_API_KEY }}
        run: |
          cat > src/test/resources/application.yaml << EOF
          api:
            key: ${RP_API_KEY}

          base:
            url: https://demo.reportportal.io/api/v1
            projectName: default_personal

          url:
            launches: https://demo.reportportal.io/ui/#default_personal/launches/all
          EOF

      - name: Run API Tests
        run: mvn -B test -DsuiteXmlFile=src/test/resources/testng-api.xml

      - name: Run UI Tests
        run: mvn -B test -DsuiteXmlFile=src/test/resources/testng-ui.xml

